version: '3'

services:
  strapi:
    build: .
    container_name: strapi
    restart: unless-stopped
    env_file: .env
    ports:
      - '1337:1337'
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app

  postgres:
    image: postgres:13
    container_name: postgres
    restart: unless-stopped
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres_data:
